# =============================================================================
# MOBIUS OS - Cloud Build Configuration for GCP Deployment
# =============================================================================
#
# PREREQUISITES:
# 1. Create Cloud SQL PostgreSQL instance:
#    gcloud sql instances create mobius-db \
#      --database-version=POSTGRES_15 \
#      --tier=db-f1-micro \
#      --region=us-central1
#
# 2. Create database and user:
#    gcloud sql databases create mobius --instance=mobius-db
#    gcloud sql users create mobius_app --instance=mobius-db --password=YOUR_PASSWORD
#
# 3. Store secrets in Secret Manager:
#    echo -n "YOUR_PASSWORD" | gcloud secrets create db-password --data-file=-
#    echo -n "YOUR_SECRET_KEY" | gcloud secrets create app-secret-key --data-file=-
#
# MANUAL DEPLOYMENT:
#   gcloud builds submit --config cloudbuild.yaml \
#     --substitutions=_TAG=$(git rev-parse --short HEAD)
#
# AUTO DEPLOYMENT: Set up Cloud Build trigger on push to main
# =============================================================================

substitutions:
  _SERVICE_NAME: mobius-os-backend
  _REGION: us-central1
  _CLOUDSQL_INSTANCE: mobius-db
  _TAG: latest

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - './backend/Dockerfile'
      - './backend'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:${_REGION}:${_CLOUDSQL_INSTANCE}'
      - '--set-env-vars'
      - 'DATABASE_MODE=cloud,ENABLE_FIRESTORE=true,FLASK_ENV=production,FLASK_DEBUG=0,CLOUDSQL_CONNECTION_NAME=$PROJECT_ID:${_REGION}:${_CLOUDSQL_INSTANCE},POSTGRES_DB_CLOUD=mobius,POSTGRES_USER_CLOUD=postgres,GCP_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'POSTGRES_PASSWORD_CLOUD=db-password:latest,SECRET_KEY=app-secret-key:latest'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
    waitFor: ['push']

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
