"""
Base conversation agent
- Captures user message
- Replays user message (echo back)
- Sends acknowledgement
- Uses session_id from frontend
"""

from datetime import datetime


class ConversationAgent:
    """
    Base conversation agent
    - Captures user message
    - Replays user message (echo back)
    - Sends acknowledgement
    - Uses session_id from frontend
    """
    
    def process_message(self, user_message: str, session_id: str, context: dict = None):
        """
        Process user message
        Args:
            user_message: User's message
            session_id: Session ID generated by frontend
            context: Optional context dict
        Returns: dict with replayed message and acknowledgement
        """
        if context is None:
            context = {}
        
        # Validate session_id
        if not session_id:
            raise ValueError("session_id is required")
        
        # 1. Capture user message (with session_id)
        captured = self._capture_message(user_message, session_id, context)
        
        # 2. Replay user message
        replayed = self._replay_message(user_message)
        
        # 3. Send acknowledgement
        acknowledgement = self._send_acknowledgement(user_message)
        
        return {
            "success": True,
            "session_id": session_id,
            "replayed": replayed,
            "acknowledgement": acknowledgement,
            "captured": captured
        }
    
    def _capture_message(self, user_message: str, session_id: str, context: dict):
        """Capture and store user message"""
        # For now, just return confirmation
        # Later: store in Firestore with session_id
        return {
            "message": user_message,
            "session_id": session_id,
            "timestamp": self._get_timestamp(),
            "context": context
        }
    
    def _replay_message(self, user_message: str):
        """Replay user message (echo back)"""
        return f"You said: {user_message}"
    
    def _send_acknowledgement(self, user_message: str):
        """Send acknowledgement message"""
        return "Message received and acknowledged."
    
    def _get_timestamp(self):
        """Get current timestamp"""
        return datetime.utcnow().isoformat()
